---
# tasks file for join-linux
- include_tasks: centos7.yml
  when: ansible_distribution == "CentOS" and ansible_distribution_version == "7.8", ">="

- include_tasks: ubuntu20.yml
  when: ansible_distribution == "Ubuntu" and ansible_distribution_version == "20", ">="
